name: realtime-rabies
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.74
  - coreutils=8.25
  - nodejs=12.11.1
  - mafft
  - medaka=1.0.3
  - minimap2=2.17
  - pip
  - python=3.6
  - snakemake-minimal=5.8.1
  - racon=1.4.20
  - artic-network::rampart=1.2
  - pip:
    - msgpack==0.6.2
    - binlorry==1.3.1
    - git+https://github.com/artic-network/Porechop.git@v0.3.2pre
    - git+https://github.com/rmcolq/postbox.git@v0.5
    - h5py==2.7.1 
    - pytools
    - scipy==1.3.1
    - tensorflow==1.14.0
    
