##### Where is the data? #####

input_path: path/to/data
annotated_path: annotations
output_path: analysis

##### Mapping reference panel #####

references_file: ../../references.fasta
scheme_file: path/to/scheme

##### Barcodes to process #####


##### Read length filtering range #####

min_read_length: 150
max_read_length: 3000

##### Read thresholds #####

min_reads: 20
min_pcent: 0.005

##### Analysis Stem #####
